dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=github setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: crm8Cd9Kjtf961eQ4kNPwhcxj5Qf2b++xFmdgLcHzvsic1GdD/e+/P5ScUiamVJm9/yXF/VRCy+7wOilx5REXJqQQz6DBO5nQH3lIr7jjV7luAJts534S0Bc1N8dVhmLldI08VJpJJ2+EY9AVXOpwldYBvDStKY4SL3Ril/Cr3Y=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
