name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, rc]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: pip install -r requirements.txt
      - run: |
          pip install black
          black . --check
        if: matrix.python-version == '3.12'
      - run: |
          pip install pytest
          pytest
      - run: python setup.py test
        if: matrix.python-version != '3.12' && matrix.python-version != 'latest'
